In [3]:
#1.Cтворіть одновимірний масив (вектор) з добутками парних чисел на їхні попередні непарні числа, починаючи з 2, та виведіть його значення.

result = []
#Перше парне число
current_even = 2

for _ in range(10):

    current_odd = current_even - 1
#Множення парного на попереднэ непарне
    product = current_even * current_odd
    result.append(product)
#Наступне парне число
    current_even += 2
#Вивід результату
print(result)


[2, 12, 30, 56, 90, 132, 182, 240, 306, 380]


In [5]:
#2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями квадратів відстаней між кожною парою натуральних чисел, починаючи з 1, та виведіть його значення.

import numpy as np

# Створюємо матрицю розміром 3x3
matrix = np.zeros((3, 3))

# Заповнюємо матрицю квадратами відстаней
for i in range(3):
    for j in range(3):
        distance = (i+1 - (j+1))**2
        matrix[i][j] = distance

# Виводимо матрицю
print(matrix)


[[0. 1. 4.]
 [1. 0. 1.]
 [4. 1. 0.]]


In [7]:
#3.Створіть масив розміром 5x5, заповніть його випадковими дійсними числами від -2 до 2 та знайдіть середнє за модулем значення його елементів.
import numpy as np

# Створюємо масив розміром 5x5 з випадковими дійсними числами від -2 до 2
random_array = np.random.uniform(-2, 2, size=(5, 5))

# Знаходимо модуль кожного елемента масиву за допомогою бібліотеки numpy
abs_array = np.abs(random_array)

# Знаходимо середнє значення модулів елементів масиву за допомогою бібліотеки numpy
average_abs_value = np.mean(abs_array)

print("Масив:")
print(random_array)
print("Середнє за модулем значення елементів масиву:", average_abs_value)


Масив:
[[ 1.61647212  0.58268315 -0.48841797 -0.03046966 -0.39718516]
 [-0.8598906   1.48185018  1.59968474 -0.16625102 -0.38443145]
 [ 0.22418984 -0.42606834 -0.90946676  0.5732695   1.94186624]
 [ 0.88345698 -0.65433885  1.25861706 -0.92884089 -1.57514334]
 [-0.34403455 -1.67356354 -1.83046744 -1.17140879  1.19520569]]
Середнє за модулем значення елементів масиву: 0.9278909552159901


In [9]:
#4.Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та обчисліть суму елементів, які менше середнього значення.
import numpy as np

array = np.random.rand(5, 5)

mean_value = np.mean(array)

less_than_mean = array[array < mean_value]

sum_of_less_than_mean = np.sum(less_than_mean)

print("Масив:")
print(array)
print("\nСереднє значення:", mean_value)
print("\nСума елементів, які менше середнього значення:", sum_of_less_than_mean)


Масив:
[[0.14487997 0.27998346 0.54637235 0.52269936 0.16944146]
 [0.81977427 0.75457377 0.14740777 0.26703148 0.80155627]
 [0.09640506 0.0296697  0.67771247 0.8496408  0.93937845]
 [0.96484794 0.44471253 0.33718776 0.42894851 0.92331751]
 [0.09727366 0.54635584 0.8791125  0.40289322 0.76147386]]

Середнє значення: 0.5133059988264592

Сума елементів, які менше середнього значення: 2.8458345850190874


In [10]:
#5.Створіть два одновимірних масиви розміром 7, заповніть їх випадковими дійсними числами від -2 до 2 та виконайте на них поелементні операції додавання, віднімання ta множення.
import numpy as np

size = 7

array1 = np.random.uniform(-2, 2, size)
array2 = np.random.uniform(-2, 2, size)

print("Перший масив:")
print(array1)
print("\nДругий масив:")
print(array2)

sum = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("\nРезультат додавання:")
print(sum)
print("\nРезультат віднімання:")
print(subtraction)
print("\nРезультат множення:")
print(multiplication)


Перший масив:
[ 0.34543633  1.64340479  1.69237141 -1.13889105 -0.24261866  0.83995319
  0.94603644]

Другий масив:
[-1.9790049   1.02889189 -0.45190358 -0.61109262  1.80008108 -1.21773692
 -1.42043184]

Результат додавання:
[-1.63356857  2.67229669  1.24046784 -1.74998368  1.55746242 -0.37778373
 -0.4743954 ]

Результат віднімання:
[ 2.32444122  0.6145129   2.14427499 -0.52779843 -2.04269973  2.05769011
  2.36646828]

Результат множення:
[-0.68362019  1.69088587 -0.76478869  0.69596792 -0.43673325 -1.02284201
 -1.34378028]


In [11]:
#6.Створіть два вектори розміром 7, заповніть їх довільними цілими числами та знайдіть їх скалярний добуток.

import numpy as np


vector1 = np.array([2, 4, 6, 8, 10, 12, 14])
vector2 = np.array([1, 3, 5, 7, 9, 11, 13])


scalar_product = np.dot(vector1, vector2)


print("Скалярний добуток векторів:", scalar_product)


Скалярний добуток векторів: 504


In [15]:
#7.Створіть дві матриці розміром 4x2 та 2x5, заповніть їх випадковими цілими числами в діапазоні від 1 до 12 та перемножте їх між собою.
import numpy as np

# Створення матриці розміром 4x2 з випадковими цілими числами від 1 до 12
array1 = np.random.randint(1, 13, size=(4, 2))

# Створення матриці розміром 2x5 з випадковими цілими числами від 1 до 12
array2 = np.random.randint(1, 13, size=(2, 5))

#Вивід матриць
print("Матриця 1:")
print(array1)

print("Матриця 2:")
print(array2)

# Перемноження матриць за допомогою функціоналу бібліотеки Numpy
result_array = np.dot(array1, array2)

print("Результат перемноження матриць:")
print(result_array)


Матриця 1:
[[ 8 11]
 [10 10]
 [11  7]
 [ 9  6]]
Матриця 2:
[[ 5  5  2 11 10]
 [ 3  2  9  9  9]]
Результат перемноження матриць:
[[ 73  62 115 187 179]
 [ 80  70 110 200 190]
 [ 76  69  85 184 173]
 [ 63  57  72 153 144]]


In [20]:
#8.Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
import numpy as np

# Створюємо випадкову матрицю розміром 2x2 з цілими числами від 1 до 10
array = np.random.randint(1, 11, (2, 2))

print("Вихідна матриця:")
print(array)

# Знаходимо обернену матрицю
inverse_array = np.linalg.inv(array)

print("Обернена матриця:")
print(inverse_array)


Вихідна матриця:
[[10  5]
 [ 8  8]]
Обернена матриця:
[[ 0.2   -0.125]
 [-0.2    0.25 ]]


In [19]:
#9.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 10 до 50 та транспонуйте її.
import numpy as np

# Створення матриці розміром 3x3 з випадковими числами у діапазоні від 10 до 50
array = np.random.uniform(10, 50, (3, 3))

# Виведення початкової матриці
print("Початкова матриця:")
print(array)

# Транспонування матриці
transposed_array = np.transpose(array)

# Виведення транспонованої матриці
print("\nТранспонована матриця:")
print(transposed_array)


Початкова матриця:
[[12.18059751 28.63556341 46.99902794]
 [30.92537463 23.0073007  34.64144532]
 [48.85205289 17.89180986 47.09706322]]

Транспонована матриця:
[[12.18059751 30.92537463 48.85205289]
 [28.63556341 23.0073007  17.89180986]
 [46.99902794 34.64144532 47.09706322]]


In [21]:
#10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть середнє значення елементів вектору.
import numpy as np

# Створимо матрицю 3x4 з випадковими цілими числами від 1 до 10
array = np.random.randint(1, 11, size=(3, 4))

# Створимо вектор розміром 4 з випадковими дійсними числами від 0 до 1
vector = np.random.rand(4)

# Знайдемо середнє значення елементів вектору
average_value = np.mean(vector)

print("Матриця 3x4:")
print(array)
print("\nВектор:")
print(vector)
print("\nСереднє значення елементів вектору:", average_value)


Матриця 3x4:
[[4 3 7 7]
 [2 6 7 6]
 [7 4 9 4]]

Вектор:
[0.38905703 0.04677101 0.07267388 0.38660548]

Середнє значення елементів вектору: 0.22377685170111558


In [34]:
#11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть суму елементів вектору, які більше за відповідний елемент матриці.
import numpy as np

# Створення матриці розміром 2x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(2, 3)

# Створення вектора розміром 3 з випадковими цілими числами в діапазоні від 1 до 10
vector = np.random.randint(1, 11, 3)

# Виведення створеної матриці та вектора
print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)

# Ініціалізуємо змінну для зберігання суми
result = 0

# Порівнюємо кожний елемент вектора з відповідним елементом матриці
for i in range(2):
    for j in range(3):
        if vector[j] > matrix[i][j]:
            result += vector[j]

print("Сума елементів вектору, які більше за відповідний елемент матриці:", result)



Матриця:
[[0.07879046 0.29534713 0.59243518]
 [0.63121287 0.29920156 0.11294183]]
Вектор:
[6 5 9]
Сума елементів вектору, які більше за відповідний елемент матриці: 40


In [38]:
#12.Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток елементів діагоналі першої матриці.
import random

# Створюємо першу матрицю та заповнюємо її випадковими числами
matrix1 = [[random.randint(1, 10) for _ in range(4)] for _ in range(4)]
matrix2 = [[random.randint(1, 10) for _ in range(4)] for _ in range(4)]

# Виводимо  матриці
print("Перша матриця:")
for row in matrix1:
    print(row)

print("\nДруга матриця:")
for row in matrix2:
    print(row)


# Обчислюємо добуток елементів діагоналі першої матриці
diagonal_product = 1
for i in range(4):
    diagonal_product *= matrix1[i][i]

print(f"Добуток елементів діагоналі першої матриці: {diagonal_product}")


Перша матриця:
[7, 5, 6, 2]
[6, 6, 10, 8]
[6, 9, 3, 4]
[4, 4, 9, 4]

Друга матриця:
[7, 9, 9, 8]
[5, 3, 10, 8]
[8, 3, 6, 9]
[6, 2, 7, 2]
Добуток елементів діагоналі першої матриці: 504


In [39]:
#13.Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть суму їх елементів.
import numpy as np

# Створюємо першу матрицю 3x3 з випадковими числами в діапазоні від -1 до 1
matrix1 = np.random.uniform(-1, 1, (3, 3))

# Створюємо другу матрицю 3x3 з випадковими числами в діапазоні від -1 до 1
matrix2 = np.random.uniform(-1, 1, (3, 3))

# Знаходимо суму елементів обох матриць
sum_of_matrices = matrix1 + matrix2

print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)
print("\nСума матриць:")
print(sum_of_matrices)


Перша матриця:
[[ 0.71186708  0.46723733 -0.98575934]
 [-0.09173114  0.42501332  0.65779125]
 [ 0.62081834  0.66926948  0.4979616 ]]

Друга матриця:
[[ 0.59606145 -0.8431465   0.82207536]
 [-0.26868845 -0.21967515 -0.32691112]
 [ 0.20872329  0.33084516 -0.36297801]]

Сума матриць:
[[ 1.30792853 -0.37590917 -0.16368398]
 [-0.36041959  0.20533817  0.33088013]
 [ 0.82954164  1.00011464  0.13498359]]


In [40]:
#14.Створіть матрицю розміром 6x6, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть найбільший елемент матриці.
import numpy as np

# Створюємо матрицю розміром 6x6 з випадковими дійсними числами в діапазоні від -10 до 10.
matrix = np.random.uniform(-10, 10, (6, 6))

# Знаходимо найбільший елемент матриці.
max_element = np.max(matrix)

print("Матриця:")
print(matrix)
print("\nНайбільший елемент матриці:", max_element)


Матриця:
[[ 9.43183036  7.03021312  6.87775537 -7.90527254  2.20945295  5.09608443]
 [-1.85362751 -4.06979476 -7.51901295 -1.29138041  2.6039373   1.00550557]
 [ 1.79417106  9.92832656 -6.91185804 -4.84681209  4.72975794 -3.28774933]
 [ 9.67102594  0.03585417 -2.91655816  8.55994332  1.68876744  7.64309681]
 [-0.01793498  7.90522467 -9.35613417 -9.56937956 -3.1299693  -4.37432485]
 [ 7.24323151  5.65700382  0.04575065 -0.1053305   9.0851007   2.27586986]]

Найбільший елемент матриці: 9.92832656264288


In [47]:
#15.Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить кількість нульових елементів в кожному рядку матриці.
import numpy as np

# Створення матриці 5x5 з випадковими числами в діапазоні від -0.5 до 0.5
matrix = np.random.uniform(-0.5, 0.5, (5, 5))

# Знаходження вектора-стовпчика з кількістю нульових елементів в кожному рядку матриці
zero_counts = np.count_nonzero(matrix == 0, axis=1)

print("Матриця:")
print(matrix)
print("Вектор з кількістю нульових елементів в кожному рядку:")
print(zero_counts)


Матриця:
[[-0.48083845  0.35356824  0.01505244  0.28998518 -0.44849896]
 [-0.38884165  0.23815784 -0.32877164 -0.24646129  0.49332494]
 [ 0.29982031  0.0491901  -0.01028049  0.01050368  0.10528543]
 [ 0.17138302 -0.0483735  -0.39898777 -0.28909976  0.31060435]
 [-0.00128854  0.13830813 -0.01727507 -0.36487983 -0.1121103 ]]
Вектор з кількістю нульових елементів в кожному рядку:
[0 0 0 0 0]


In [ ]:
#На практичному занятті було виконано роботу з матрицями та векторами, та проведено різні дії з ними при різних умовах розмірів да заданих чисел